### ISSUE TITLE
 Invalid login: 535 Error: authentication failed

### ISSUE THREAD

**Issue by wzc0x0** [lhlybly/node_12306#1]
车票查询没有问题，但是同样是163邮箱，邮件却发不出去报错

**Comment by wzc0x0** [comment]
{ Error: Invalid login: 535 Error: authentication failed
    at SMTPConnection._formatError (C:\Users\WZC\node_12306\node_modules\smtp-connection\lib\smtp-connection.js:528:15)
    at SMTPConnection._actionAUTHComplete (C:\Users\WZC\node_12306\node_modules\smtp-connection\lib\smtp-connection.js:1231:30)
    at SMTPConnection.<anonymous> (C:\Users\WZC\node_12306\node_modules\smtp-connection\lib\smtp-connection.js:319:22)
    at SMTPConnection._processResponse (C:\Users\WZC\node_12306\node_modules\smtp-connection\lib\smtp-connection.js:669:16)
    at SMTPConnection._onData (C:\Users\WZC\node_12306\node_modules\smtp-connection\lib\smtp-connection.js:493:10)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)
  code: 'EAUTH',
  response: '535 Error: authentication failed',
  responseCode: 535,
  command: 'AUTH PLAIN' }

**Comment by hongrunhui** [comment]
认证失败，你要到163邮箱设置里面去开启smtp。
![image](https://cloud.githubusercontent.com/assets/9162319/21952345/0c3d50a4-da54-11e6-9ca1-dc17d38e787b.png)
当然还有一种方式就是填写授权码，就是在截图里客户端授权密码里去开启，然后替换你原来的邮箱密码就可以了，这样会更安全点。

**Comment by hongrunhui** [comment]
如果解决了记得跟我说下

**Comment by wzc0x0** [comment]
果然是授权码的问题，已验证通过可以发邮件了，就连qq邮箱也需要这样鸡肋的设置。谢谢！

**Comment by wzc0x0** [comment]
不过在我这里还有一个问题，几次查询过后会报错：
undefined:1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.<anonymous> (C:\Users\WZC\node_12306\main.js:37:26)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by hongrunhui** [comment]
我现在在火车上，回去之后我看一下

**Comment by hongrunhui** [comment]
额，我觉得这可能是一时间网络不稳定造成的，我之前也出现过。解决这个问题的最简单方法就是安装forever.当退出时自动重启。
具体操作：```npm install forever -g```
```sudo forever start main.js```
还可以用pm2。这个更好用

**Comment by wzc0x0** [comment]
好的谢谢了！另外我利用了阿里大于的nodejs可以发短信的方法改造了一下，替代发邮件，觉得挺好用的，哈哈！

**Comment by hongrunhui** [comment]
阿里大鱼免费么？

**Comment by wzc0x0** [comment]
注册送10元，可以发200来条短信
