### ISSUE TITLE
现在12306查票的返回数据经过加密了

### ISSUE THREAD

**Issue by cyf0611** [lhlybly/node_12306#17]
大神，你会解析吗，求更新

**Comment by hongrunhui** [comment]
嗯，以后会更新吧，但是现在在公司挺忙的，没时间

**Comment by hongrunhui** [comment]
楼上大兄弟就因为你的头像，我follow你了，哈哈。

**Comment by cyf0611** [comment]
哈哈

**Comment by hongrunhui** [comment]
现在已支持重新使用了

**Comment by ZhongqiXiao** [comment]
JSON数据出错 TypeError: Cannot read property 'result' of undefined
    at IncomingMessage.<anonymous> (J:\Git-Repository\node_12306\main.js:165:22)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

请问这个怎么解决啊
