### ISSUE TITLE
node main.js error

### ISSUE THREAD

**Issue by saltedfishboy** [lhlybly/node_12306#26]
这个是我的json 
{
    "time": "2018-02-06",
    "from_station": 
      {
        "name": "南京",
        "code": "NJH",
        "pinyin": "nanjing",
        "suoxie": "nj",
        "other": "54@njn"
      },
    "end_station": {
      "name": "西安",
      "code": "XAY",
      "pinyin": "xian",
      "suoxie": "xa",
      "other": "69@xan"
    },
    "train_num": [
      "Z86",
      "Z40"
    ],
    "your_mail": "",
    "mail_pass": "",
    "receive_mail": ""
  }

**Comment by hongrunhui** [comment]
你想说什么？

**Comment by saltedfishboy** [comment]
您好我这边运行报错
JSON数据出错,请检查输入配置是否正确 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (D:\workSpace\node_12306-master_2\node_12306-master\main.js:279:22)
    at emitNone (events.js:120:20)
    at IncomingMessage.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
新手

**Comment by hongrunhui** [comment]
返回的数据不对，你看看你那天是否有这几辆火车的信息？

**Comment by saltedfishboy** [comment]
是有的这两趟车次

**Comment by hongrunhui** [comment]
修复错误了

**Comment by saltedfishboy** [comment]
还是报我json异常 0.0 
{
    "time": "2018-02-06",
    "from_station": {
        "name": "合肥",
        "code": "HFH",
        "pinyin": "hefei",
        "suoxie": "hf",
        "other": "34@hfx"
    },
    "from_station_": "合肥",
    "end_station": {
      "name": "西安",
      "code": "XAY",
      "pinyin": "xian",
      "suoxie": "xa",
      "other": "69@xan"
    },
    "end_station_": "西安",
    "train_num": [
      "K62"
    ],
    "your_mail": "dudooo@foxmail.com",
    "mail_pass": "",
    "receive_mail": "dudooo@foxmail.com"
  }
这是我的json 是哪里不对么我这里吧邮箱换成了qq的  是我哪里操作姿势不断么0.0
var transporter = nodemailer.createTransport({
			host: "smtp.qq.com",
			secureConnection: true,
			port: 465,//端口，这里端口我看扣扣有两个
			auth: {
				user: config.your_mail,/
				pass: config.mail_pass,/
			}
		});

**Comment by hongrunhui** [comment]
你json报的异常是啥，应该会输出错误信息的

**Comment by saltedfishboy** [comment]
还是这个 JSON数据出错,请检查输入配置是否正确 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (D:\workSpace\node_12306-master2\node_12306-master\main.js:323:22)
    at emitNone (events.js:120:20)
    at IncomingMessage.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
出错的数据：

**Comment by jimmyczm** [comment]
我的也是这个错误 @saltedfishboy 
----
找到问题了，日期格式设置成2018-02-02这种就好了

**Comment by smalltimoo** [comment]
再监听过程中偶尔会有一次这种情况发生，原因不明
![image](https://user-images.githubusercontent.com/19339167/34815016-c08b1a4c-f6ea-11e7-8044-ee1588f752e1.png)
目标时间我已经补了0

**Comment by liangyafeng** [comment]
leftTicket/query
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38) code: 'UNABLE_TO_VERIFY
_LEAF_SIGNATURE' }

**Comment by leinue** [comment]
同，我也是这个错误

**Comment by leinue** [comment]
这个错误不报之后就报
leftTicket/query
/mnt/node_12306/main.js:251
		for (var cr = 0; cr < ct.length; cr++) {
		                         ^

TypeError: Cannot read property 'length' of undefined

这个错误

随机的

**Comment by douziyh** [comment]
不能用q邮箱吗？输完信息后没有反应
