### ISSUE TITLE
如果过于频繁的访问，IP会被封掉吗？程序中能不能对此做一些优化啊？

### ISSUE THREAD

**Issue by qizhenjiang** [lhlybly/node_12306#9]

**Comment by qizhenjiang** [comment]
我一秒访问一次，前两天还可以，今天一跑程序就报错，是不是因为ip被封掉的额原因啊？

**Comment by hongrunhui** [comment]
当然会封ip啊，这个没必要一秒一次啊，一分钟一次足以。

**Comment by qizhenjiang** [comment]
换了ip还是这样  很纳闷啊？能帮我看下是什么原因引起的吗？
"D:\webstorm\WebStorm 2016.2.3\bin\runnerw.exe" E:\node\node.exe E:\Node_Project\main.js
scheduleCronstyle:Thu Jan 19 2017 13:57:13 GMT+0800 (中国标准时间)
E:\Node_Project\main.js:43
    	for(var i=0;i<jsonData.length;i++){
    	                      ^

TypeError: Cannot read property 'length' of undefined
    at IncomingMessage.<anonymous> (E:\Node_Project\main.js:43:28)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
<Buffer 7b 22 73 74 61 74 75 73 22 3a 66 61 6c 73 65 2c 22 63 5f 75 72 6c 22 3a 22 6c 65 66 74 54 69 63 6b 65 74 2f 71 75 65 72 79 5a 22 2c 22 63 5f 6e 61 6d ... >
{"status":false,"c_url":"leftTicket/queryZ","c_name":"CLeftTicketUrl"}

**Comment by hongrunhui** [comment]
![image](https://cloud.githubusercontent.com/assets/9162319/22095874/2270489c-de53-11e6-849b-e91bba3dbb59.png)
估计12306采取了措施了，被封了

**Comment by hongrunhui** [comment]
我先看看能不能解决这个问题
